// user related
export const CREATE_ROLE = "CREATE_ROLE"
export const UPDATE_ROLE = "UPDATE_ROLE"
export const CREATE_POLICY_GRUPS = "CREATE_POLICY_GRUPS"
export const UPDATE_POLICY_GRUPS = "UPDATE_POLICY_GRUPS"